// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`\`done()\` should not be called more than once 1`] = `
FAIL __tests__/index.test.js
  \`done()\` called more than once
    ✕ should fail
    ✕ should fail inside a promise
  multiple \`done()\` inside a hook
    ✕ should fail

  ● \`done()\` called more than once › should fail

    Expected done to be called once, but it was called multiple times.

       8 |   it('should fail', done => {
       9 |     done();
    > 10 |     done();
         |     ^
      11 |   });
      12 | 
      13 |   it('should fail inside a promise', done => {

      at Object.done (__tests__/index.test.js:10:5)

  ● \`done()\` called more than once › should fail inside a promise

    Expected done to be called once, but it was called multiple times.

      15 |       .then(() => {
      16 |         done();
    > 17 |         done();
         |         ^
      18 |       })
      19 |       .catch(err => err);
      20 |   });

      at done (__tests__/index.test.js:17:9)

  ● multiple \`done()\` inside a hook › should fail

    Expected done to be called once, but it was called multiple times.

      24 |   beforeEach(done => {
      25 |     done();
    > 26 |     done();
         |     ^
      27 |   });
      28 | 
      29 |   it('should fail', () => {

      at Object.done (__tests__/index.test.js:26:5)
`;
